project:
  type: website

website:
  title: "My Portfolio"
  favicon: favicon.png  # Make sure to put an image named favicon.png in your folder
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmos      # This provides a clean, modern font automatically
    css: styles.css
    toc: true